version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app
    ports:
        - "5431:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - postgres

